#!/bin/bash

export XDG_CURRENT_DESKTOP=bspwm
export WM=bspwm
export _JAVA_AWT_WM_NONREPARENTING=1

xrdb -merge ~/.Xresources
sxhkd -m 1 > /tmp/sxhkd.log 2> /tmp/sxhkd2.log &

bspc monitor DP-0 -d Q W E R T
bspc monitor DP-2 -d 1 2 3 4 5

# apps
bspc rule -a Chromium desktop=^9
bspc rule -a firefox desktop=^9
bspc rule -a Zathura state=tiled desktop=^2
bspc rule -a discord desktop=^5
bspc rule -a Thunderbird desktop=^4
bspc rule -a spotify desktop=^3

bspc config window_gap 15

bspc config split_ratio 0.4
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config click_to_focus button1

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config focused_border_color "#586e75"
bspc config active_border_color "#586e75"
bspc config normal_border_color "#002b36"

bspc config automatic_scheme spiral

xsetroot -cursor_name left_ptr
hsetroot -fill ~/.config/bspwm/pink-flowers.jpg
setxkbmap -layout se
#xinput --set-prop 'pointer:Kingston HyperX Pulsefire Core' 'libinput Accel Speed' -0.8
xinput --set-prop 'pointer:Cooler Master Technology Inc. MM710 Gaming Mouse' 'libinput Accel Speed' -0.96

for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar -r bar1 &
done

dunst &
wmname LG3D

xrandr --output 'DP-2' --primary
numlockx on
firefox &
discord-canary &
thunderbird &
echo "Starting picom">/tmp/picom.log
pgrep -u "$USER" picom >/dev/null || \
	picom -bc --shadow-exclude 'class_g = "Polybar"' -o 0.2 -r 0 -l 5 -t 5 >>/tmp/picom.log 2>&1
