#!/bin/bash

export XDG_CURRENT_DESKTOP=bspwm
export WM=bspwm
export _JAVA_AWT_WM_NONREPARENTING=1

xrdb -merge ~/.Xresources
sxhkd -m 1 > /tmp/sxhkd.log 2> /tmp/sxhkd2.log &

bspc monitor -d 1 2 3 4 5 Q W E R T

# apps
bspc rule -a Chromium desktop=^9
bspc rule -a Zathura state=tiled desktop=2
bspc rule -a discord desktop=^10
bspc rule -a Thunderbird desktop=^4
bspc rule -a spotify desktop=^5

bspc config window_gap 15

bspc config split_ratio 0.4
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config click_to_focus button1

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config automatic_scheme spiral

xsetroot -cursor_name left_ptr
hsetroot -fill ~/.config/bspwm/jayart-kulkarni-boat.jpg
polybar -r bar1 &
setxkbmap -layout no
xinput --set-prop 'pointer:Kingston HyperX Pulsefire Core' 'libinput Accel Speed' -0.9

dunst &
set_wmname LG3D

xrandr --output 'HDMI-A-1' --primary
numlockx on
chromium &
discord-canary &
thunderbird &
echo "Starting picom">/tmp/picom.log
pgrep -u "$USER" picom >/dev/null || \
	picom -bc --shadow-exclude 'class_g = "Polybar"' -o 0.2 -r 0 -l 5 -t 5 >>/tmp/picom.log 2>&1
